### ISSUE TITLE
Mac instructions did not work for me

### ISSUE THREAD

**Issue by bjartek** [brendan-rius/c-jwt-cracker#1]
On my mac those instructions did not work. I had to do

make OPENSSL=/usr/local/opt/openssl/include and replace -lssl for -L/usr/local/opt/openssl/lib in the Makefile.

brew link openssl says
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

./jwtcrack eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE
Secret is "Sn1f"
Time taken 8 seconds 990 milliseconds

**Comment by brendan-rius** [comment]
Fixed it. The command is now:

```
make OPENSSL=/usr/local/opt/openssl/include OPENSSL_LIB=-L/usr/local/opt/openssl/lib
```

thanks! :)
