### ISSUE TITLE
More Optimization

### ISSUE THREAD

**Issue by varunpalekar** [brendan-rius/c-jwt-cracker#2]
More optimization
============

### Multi-processing: 
You can optimize more by using multiprocessing instead of using multi-threading . 
You can get result more quickly if you do this through multi-processing (i.e., run code on parallel CPUs). 
This is because if you are going towards multi-threading then you are giving OS to schedule the threads but in practical you can only run threads equal to CPU number of system. So, you just wasting time of program by Process scheduling. 
If you can use multi-processing way, then it will be better optimized.  You can test the results. 

### Hardware SHA extension
Other then that you can also use hardware SHA extension if it is available in CPU. https://en.wikipedia.org/wiki/Intel_SHA_extensions

Thanks, hope above suggestion will help and make better code.

**Comment by brendan-rius** [comment]
Thanks for pointing that out.
You're welcome to make a pull request to implement this if you want :)

For real optimizations, should run on GPUs (like Hashcat, but I can't make it work it always gives me some weird error about length)
