### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by rmscoal** [brendan-rius/c-jwt-cracker#25]
I am running on Macbook M2 Pro and I have installed OpenSSL by `brew install openssl`

Then I ran the `make` command like the following:
```bash 
$ make OPENSSL=/usr/local/opt/openssl/include OPENSSL_LIB=-L/usr/local/opt/openssl/lib
```
And I got this error
```bash
gcc -I /usr/local/opt/openssl/include -g -std=gnu99 -O3 -I/opt/homebrew/opt/openjdk/include  -c -o main.o main.c
main.c:13:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [main.o] Error 1
```

Can anyone help me?

**Comment by Apeayulsa** [comment]
/usr/local replace  /opt/homebrew . so---
make OPENSSL=/opt/homebrew/opt/openssl/include OPENSSL_LIB=-L/opt/homebrew/opt/openssl/lib

**Comment by rmscoal** [comment]
It works, thank you very much !! Helps a lot.
